addons:
  apt:
    packages:
    - doxygen
    - graphviz
    - autoconf
    - automake
    - libtool
    - m4
    - gtk-doc-tools
    - pkg-config
    - libxslt1-dev
    - intltool
    - gettext
    - python2-dev
    - python-mutagen
    - python-setuptools
    - libsqlite3-dev
    - libglib2.0-dev
    - libxml2-dev
    - libimobiledevice-dev
    - libgdk-pixbuf2.0-dev

language: c

python:
    - "2.7"

script: cp README.old README && cp ChangeLog.old ChangeLog && ./autogen.sh && make && make check

install: true

sudo: false

notifications:
  irc: "chat.freenode.net#code-hell"

